sudo: required

services:
  - docker

language: php
php:
  - '7.0'

script:
  - composer install --no-dev
  - php app/console cache:clear -e prod
  - php app/console doctrine:schema:drop --force
  - php app/console doctrine:schema:update --force

after_success:
  - sh ./.travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh