services:
    gfb_chat_bot.router:
        class: GFB\ChatBotBundle\Routing\Router
        arguments:
            - "@annotation_reader"

#    gfb_chat_bot.example:
#        class: GFB\ChatBotBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
